require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")
require File.join(File.dirname(`node --print "require.resolve('react-native-unimodules/package.json')"`), "cocoapods")


platform :ios, '11.0'

target 'reactNativeWebBrowserApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'reactNativeWebBrowserAppTests' do
    inherit! :complete
    # Pods for testing
  end

  use_unimodules!

  pre_install do |installer|
    installer.pod_targets.each do |target|
      if target.name == "UMPermissionsInterface"
        # https://github.com/expo/expo/issues/6477
        target.dependent_targets << installer.pod_targets.select{|t| t.pod_name == 'UMCore'}.first
      end
      if target.name == 'UMReactNativeAdapter'
        target.dependent_targets << installer.pod_targets.select{|t| t.pod_name == 'React-CoreModules'}.first
      end
    end
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
